### ISSUE TITLE
Doesn't work with node v0.12

### ISSUE THREAD

**Issue by anler** [rejeep/nvm.el#2]
Hi, with the last version of node doesn't work, I think because the the lack of a `v0.12...` directory inside `~/.nvm` root (it is inside `~/.nvm/versions`:

```
tree ~/.nvm/versions -L 2
.nvm/versions
└── node
    └── v0.12.7

2 directories, 0 files
```

**Comment by robbyoconnor** [comment]
Hit with this issue as well...

**Comment by rejeep** [comment]
Does this work for you guys? https://github.com/rejeep/nvm.el/pull/3

**Comment by anler** [comment]
@rejeep it does work for me :+1:

**Comment by rejeep** [comment]
#3 is merged
