### ISSUE TITLE
Add interactive function to select node version and comint mode to run node

### ISSUE THREAD

**Issue by stefano-m** [rejeep/nvm.el#6]
Hello @rejeep,

based on

* http://www.williamjohnbert.com/2014/02/using-a-node-repl-with-emacs/
* http://github.com/porterjamesj/virtualenvwrapper.el
* https://masteringemacs.org/article/comint-writing-command-interpreter

I have written an interactive function that allows the user to select a version of node and a major mode derived from comint to run node.

What do you think about integrating it with nvm.el?

I will need some help to add tests, but I am willing to do it if you are interested in merging the code.

The code can be found at

https://notabug.org/stefano-m/.emacs.d/src/master/site-lisp/nodejs.el  (note that I am not an Emacs-Lisp expert!)

Thanks,

-- Stefano

**Comment by rejeep** [comment]
Hey,

I don't think it should be a part of the `nvm.el` lib, which is a library rather than a package intended for interactive use. If you only want the lib, you should not get all the interactive stuff.

As I see it, there are two different possibilities:

1. Keep it in a separate repo
2. Add a new file in this repo, called for example `nvm-repl`

No matter the solution, they should still be two different EPLA packages.

What would you prefer?

**Comment by stefano-m** [comment]
Hi,

I see your point.

The stuff I have written has some overlap with [js-comint](https://github.com/redguardtoo/js-comint). For me, the advantage is that I can chose any version of node with npm, but my code lacks a lot of functionality (e.g. ``send-region``, etc.).

I was thinking of submitting a PR here so that the code would be properly reviewed and supported. If that's OK with you, I am happy to add a new file to this repo, but I'll probably still need some guidance on testing etc.

On the other hand, maybe that kind of code should go into js-comint instead?

**Comment by rejeep** [comment]
Hmm, yeah, an option would be to add support for nvm in js-comint, just as [rspec-mode has support for rvm](https://github.com/pezra/rspec-mode/blob/master/rspec-mode.el#L139-L142).

**Comment by stefano-m** [comment]
Cool, I'll try and see if I can get it working with js-comint.

Thanks!

**Comment by rejeep** [comment]
Sure thing. Let me know when you have something, it seems like an interesting project! :+1:
