### ISSUE TITLE
file-error "Opening directory" "no such file or directory" "/home/foo/.nvm/versions

### ISSUE THREAD

**Issue by shakthimaan** [rejeep/nvm.el#9]
I am using GNU Emacs 24.5.2 (x86_64) on Ubuntu 15.04. I have Node.js installed as per the documentation under "How To Install Using NVM" from:

https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-an-ubuntu-14-04-server

For my Emacs setup, I have the following in Cask:
```
(depends-on "nvm")
```

My Emacs start-up .el includes the following:
```
(require 'nvm)
(setq exec-path (append '("/home/foo/.nvm") exec-path))

(js-do-use-nvm)

(js-select-node-version) ;; file-error "Opening directory" "no such file or directory" "/home/foo/.nvm/versions"

(nvm-use "4.4.3") ;; file-error "Opening directory" "no such file or directory" "/home/foo/.nvm/versions"
```

In a gnome-terminal, I am able to use "node -v", and my ~/.bashrc has the following:
```
export NVM_DIR="/home/shakthi/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
```

Output of "nvm ls"
```
->    v4.4.3
      system
default -> node (-> N/A)
```
What could I be missing?

**Comment by rejeep** [comment]
What is in `/home/foo/.nvm`? The `versions` directory is used for more recent versions of Nvm IIRC.

**Comment by shakthimaan** [comment]
```
$ ls ~/.nvm
alias  bash_completion  bin  CONTRIBUTING.md  current  install.sh  LICENSE.md  Makefile  nvm-exec  nvm.sh  package.json  README.markdown  test  update_test_mocks.sh  v4.4.3
```

**Comment by shakthimaan** [comment]
I used "emacs --debug-init" and it actually prompted me for the Node.js version. I have it working now. My setup configuration file is at:

https://github.com/shakthimaan/cask-dot-emacs/blob/master/etc/init-js.el
